---
- name: onyk
  hosts: all
  become: yes

  tasks:
    - name: Install python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Set pip3 as default pip
      alternatives:
        name: pip
        path: /usr/bin/pip3

    - name: Set python3 as default python
      alternatives:
        name: python
        path: /usr/bin/python3

    - name: Install openjdk
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install mariadb-server
      apt:
        name: mariadb-server
        state: present

    - name: Start mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create database
      mysql_db:
        name: my_database
        state: present

    - name: Create table
      mysql_query:
        login_db: my_database
        query: |
          CREATE TABLE IF NOT EXISTS my_table (
            id INT PRIMARY KEY AUTO_INCREMENT,
            name VARCHAR(100)
          );

    - name: Create MOTD file
      copy:
        content: "Ansible Managed node by 'bonifacio'"
        dest: /etc/motd

    - name: Create user with variable name
      user:
        name: "onyk"
        state: present

